spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5201314zps
    url: jdbc:mysql://localhost:3306/db02_03?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: utf-8
    cache: false
    template-loader-path: classpath:/templates
#  jpa:
#    show-sql: true
purl:
  domain: http://localhost:8080/

